users:
  email_max_length: 255
  name_max_length: 50
  password_min_length: 6
  address_max_length: 255
  phone_max_length: 15
  image_max_size: 5242880
  avatar_size: 200
  image_type: "image/jpeg,image/gif,image/png"
per_page: 10
action_edit: "edit"
suggestions:
  area_rows: 3
  per_page: 10
  size: 70
  name_max_length: 50
  description_max_length: 255
images:
  image_max_size: 5242880
  image_accept: "image/jpeg,image/gif,image/png"
one: 1
